const handleError = async (error) => {
	console.log(error);
};

module.exports = handleError;
